# Welcome to Jekyll!
#

# Site settings
title: "Portfolio   Julien Mettetal"
description: |
  Analyste Programmeur
owner: Julien Mettetal # or company name
first_published: 2024 # if migrating another site, the year of your first publish
email: jme@mtb111.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://julien5885.github.io/" # the base hostname & protocol for your site
social:
  github: "https://github.com/Julien5885//"
  linkedin-square: "https://linkedin.com//"
  google-plus-square: "https://plus.google.com/u/0/+<username>//"
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed 
